# it seems redirection using UI commands take no effect
#/control/cout/useBuffer 1
#/control/cout/setCerrFile .err
#/control/cout/setCoutFile .out

# for material scan, very forward angle
# /tracking/verbose 1
#/gun/particle geantino
#/gun/direction 2 1 20
#/gun/position 0 0 0 m

# for benchmarking
/tracking/verbose 0
/gun/particle e-
/gun/energy 10 GeV
/gun/direction 0 0 1
/gun/position 0 0 -900 cm
/gun/number 1

/run/dumpRegion


/run/beamOn 50000
